#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width            2
bspc config window_gap              8
bspc config focus_follows_pointer   true
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true
bspc config pointer_action2         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

# Application rules
bspc rule -a Zathura state=tiled

# Autostarts
xwallpaper --no-randr --stretch ~/.config/wallpaper/wallhaven-qdwqel.jpg & # set wallpaper
xset r rate 300 50 & # speed up repeated keys
xset -b & # disable beeps
xsetroot -cursor_name left_ptr & # change cursor to pointer
pidof polybar || polybar example & # panel
pidof redshift || redshift & # screen dimming
pidof xbanish || xbanish & # hide cursor
pidof sxhkd || sxhkd & # hotkeys
pidof syncthing || syncthing & # file syncronization
setxkbmap -layout gb -option caps:escape & # set keyboard layour
